// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type upfMonitorPendingPktInfo struct {
	Teid      uint32
	SrcIp     uint32
	DstIp     uint32
	SrcPort   uint16
	DstPort   uint16
	PktLen    uint32
	Direction uint8
	Valid     uint8
	Pad       [2]uint8
}

type upfMonitorSessionInfo struct {
	Seid      uint64
	UeIp      uint32
	UpfIp     uint32
	CreatedAt uint64
}

type upfMonitorTrafficCounter struct {
	Packets   uint64
	Bytes     uint64
	Timestamp uint64
}

// loadUpfMonitor returns the embedded CollectionSpec for upfMonitor.
func loadUpfMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UpfMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load upfMonitor: %w", err)
	}

	return spec, err
}

// loadUpfMonitorObjects loads upfMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*upfMonitorObjects
//	*upfMonitorPrograms
//	*upfMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUpfMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUpfMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// upfMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type upfMonitorSpecs struct {
	upfMonitorProgramSpecs
	upfMonitorMapSpecs
}

// upfMonitorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type upfMonitorProgramSpecs struct {
	KprobeGtp5gDevXmit      *ebpf.ProgramSpec `ebpf:"kprobe_gtp5g_dev_xmit"`
	KprobeGtp5gEncapRecv    *ebpf.ProgramSpec `ebpf:"kprobe_gtp5g_encap_recv"`
	KprobeGtp5gHandleSkb    *ebpf.ProgramSpec `ebpf:"kprobe_gtp5g_handle_skb"`
	KprobeGtp5gTraceDrop    *ebpf.ProgramSpec `ebpf:"kprobe_gtp5g_trace_drop"`
	KprobeIpForward         *ebpf.ProgramSpec `ebpf:"kprobe_ip_forward"`
	KprobeNfHookSlow        *ebpf.ProgramSpec `ebpf:"kprobe_nf_hook_slow"`
	KretprobeIpForward      *ebpf.ProgramSpec `ebpf:"kretprobe_ip_forward"`
	KretprobePdrFindByGtp1u *ebpf.ProgramSpec `ebpf:"kretprobe_pdr_find_by_gtp1u"`
	KretprobePdrFindByIpv4  *ebpf.ProgramSpec `ebpf:"kretprobe_pdr_find_by_ipv4"`
	TracepointKfreeSkb      *ebpf.ProgramSpec `ebpf:"tracepoint_kfree_skb"`
}

// upfMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type upfMonitorMapSpecs struct {
	AgentConfig    *ebpf.MapSpec `ebpf:"agent_config"`
	DropEvents     *ebpf.MapSpec `ebpf:"drop_events"`
	PacketEvents   *ebpf.MapSpec `ebpf:"packet_events"`
	PendingPkts    *ebpf.MapSpec `ebpf:"pending_pkts"`
	TeidSessionMap *ebpf.MapSpec `ebpf:"teid_session_map"`
	TeidStats      *ebpf.MapSpec `ebpf:"teid_stats"`
	TrafficStats   *ebpf.MapSpec `ebpf:"traffic_stats"`
	UeIpStats      *ebpf.MapSpec `ebpf:"ue_ip_stats"`
}

// upfMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type upfMonitorObjects struct {
	upfMonitorPrograms
	upfMonitorMaps
}

func (o *upfMonitorObjects) Close() error {
	return _UpfMonitorClose(
		&o.upfMonitorPrograms,
		&o.upfMonitorMaps,
	)
}

// upfMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type upfMonitorMaps struct {
	AgentConfig    *ebpf.Map `ebpf:"agent_config"`
	DropEvents     *ebpf.Map `ebpf:"drop_events"`
	PacketEvents   *ebpf.Map `ebpf:"packet_events"`
	PendingPkts    *ebpf.Map `ebpf:"pending_pkts"`
	TeidSessionMap *ebpf.Map `ebpf:"teid_session_map"`
	TeidStats      *ebpf.Map `ebpf:"teid_stats"`
	TrafficStats   *ebpf.Map `ebpf:"traffic_stats"`
	UeIpStats      *ebpf.Map `ebpf:"ue_ip_stats"`
}

func (m *upfMonitorMaps) Close() error {
	return _UpfMonitorClose(
		m.AgentConfig,
		m.DropEvents,
		m.PacketEvents,
		m.PendingPkts,
		m.TeidSessionMap,
		m.TeidStats,
		m.TrafficStats,
		m.UeIpStats,
	)
}

// upfMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type upfMonitorPrograms struct {
	KprobeGtp5gDevXmit      *ebpf.Program `ebpf:"kprobe_gtp5g_dev_xmit"`
	KprobeGtp5gEncapRecv    *ebpf.Program `ebpf:"kprobe_gtp5g_encap_recv"`
	KprobeGtp5gHandleSkb    *ebpf.Program `ebpf:"kprobe_gtp5g_handle_skb"`
	KprobeGtp5gTraceDrop    *ebpf.Program `ebpf:"kprobe_gtp5g_trace_drop"`
	KprobeIpForward         *ebpf.Program `ebpf:"kprobe_ip_forward"`
	KprobeNfHookSlow        *ebpf.Program `ebpf:"kprobe_nf_hook_slow"`
	KretprobeIpForward      *ebpf.Program `ebpf:"kretprobe_ip_forward"`
	KretprobePdrFindByGtp1u *ebpf.Program `ebpf:"kretprobe_pdr_find_by_gtp1u"`
	KretprobePdrFindByIpv4  *ebpf.Program `ebpf:"kretprobe_pdr_find_by_ipv4"`
	TracepointKfreeSkb      *ebpf.Program `ebpf:"tracepoint_kfree_skb"`
}

func (p *upfMonitorPrograms) Close() error {
	return _UpfMonitorClose(
		p.KprobeGtp5gDevXmit,
		p.KprobeGtp5gEncapRecv,
		p.KprobeGtp5gHandleSkb,
		p.KprobeGtp5gTraceDrop,
		p.KprobeIpForward,
		p.KprobeNfHookSlow,
		p.KretprobeIpForward,
		p.KretprobePdrFindByGtp1u,
		p.KretprobePdrFindByIpv4,
		p.TracepointKfreeSkb,
	)
}

func _UpfMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed upfmonitor_bpfel_x86.o
var _UpfMonitorBytes []byte
